### ISSUE TITLE
Hello World App appears in the symphony layout but after clicking Add button it doesn't appear in the left menu

### ISSUE THREAD

**Issue by arif-pixako** [symphonyoss/extension-api-examples#14]
Hello App appears in the symphony layout but after clicking Add button it doesn't appear in the left menu nor it displays the views.
In webstorm editor it gives error
var helloControllerService = SYMPHONY.services.register("hello:controller");
                                               ^

ReferenceError: SYMPHONY is not defined
    at Object.<anonymous> (c:\Users\developer\WebstormProjects\symphonyApp\src\javascript\controller.js:22:48)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by brybailey** [comment]
Hello @arif-pixako ! In your controller.html file, check that the line `<script type="text/javascript" src="https://www.symphony.com/resources/api/v1.0/symphony-api.js" charset="utf-8"></script>` is in the <body> tag. If it is, then that symphony-api.js file is not loading properly, and that will be an issue that will need to be addressed.

**Comment by bhushanpant** [comment]
Facing the same issue.

**Comment by bhushanpant** [comment]
@brybailey I checked the tag, it is placed fine is guess, still now showing on the left menu.

**Comment by arif-pixako** [comment]
Script is in the tags. 
while compiling it shows errors like this
ERROR in ./src/javascript/app.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./data in C:\Users\developer\WebstormProjects\symphony\src\javascript
 @ ./src/javascript/app.js 26:18-35

ERROR in ./src/javascript/controller.js
Module parse failed: C:\Users\developer\WebstormProjects\symphony\src\javascript\controller.js Unexpected token (235:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (235:4)
    at Parser.pp$4.raise (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:727:47)
    at Parser.pp$1.parseTopLevel (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (C:\Users\developer\WebstormProjects\symphony\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (C:\Users\developer\WebstormProjects\symphony\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (C:\Users\developer\WebstormProjects\symphony\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (C:\Users\developer\WebstormProjects\symphony\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)

webpack: Failed to compile.

Can any body provide me this app deployment video.

**Comment by bhushanpant** [comment]
@arif-pixako @brybailey any update on this?

**Comment by arif-pixako** [comment]
No update, still troubling.​

**Comment by arif-pixako** [comment]
finally the app worked by make some changes in controller.js.
i shared those changes please check that out.

**Comment by pmonks** [comment]
@arif-pixako rather than pasting in large chunks of code in issues, can you prepare a Pull Request for this change?  That will be much easier to review and merge into the upstream code.

Thanks!

**Comment by brybailey** [comment]
Hi @arif-pixako and @bhushanpant, your problem should be resolved with the recent commit. Please update your repos and let me know if you have any further issues!

**Comment by arif-pixako** [comment]
Thanks it worked.
can you please share how to load data from mysql database in the view?

**Comment by arif-pixako** [comment]
Thanks Bryan.
can you please share how to load data from mysql database in the view and
after clicking title of any post open another view in the app like Dow
Jones app in the app market?

**Comment by arif-pixako** [comment]
Hello Bryan,

I am stuck off how to load the App logo in the left menu, can you plz help
me?
